[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
sha2 = { workspace = true }
ureq = { workspace = true }
zip = { workspace = true }
magi-core = { path = "../crates/magi-core" }
tempfile = { workspace = true }
