// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeaturesConfig } from "./FeaturesConfig";
import type { IndexingConfig } from "./IndexingConfig";
import type { ModelsConfig } from "./ModelsConfig";
import type { RootConfig } from "./RootConfig";
import type { UiConfig } from "./UiConfig";

export type Config = { schema_version: number, roots: Array<RootConfig>, indexing: IndexingConfig, models: ModelsConfig, features: FeaturesConfig, ui: UiConfig, };
