// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a download failed: a stable code, localized by the UI (ADR-0010).
 */
export type DownloadError = "DownloadNetworkError" | "ChecksumMismatch" | "DiskFull" | "PermissionDenied" | "WriteFailed";
