// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Feature } from "./Feature";

/**
 * A failed command as a stable code plus parameters (SPEC.md §5.7 locale
 * neutrality). The UI localizes it; `Internal.detail` is for logs only.
 */
export type ErrorCode = { "code": "RootNotFound", path: string, } | { "code": "NestedRoot", path: string, conflicts_with: string, } | { "code": "RootAlreadyExists", path: string, } | { "code": "RootIdNotFound", id: number, } | { "code": "FileIdNotFound", file_id: number, } | { "code": "UnknownFeature", name: string, } | { "code": "DownloadInProgress", feature: Feature, } | { "code": "InvalidSetting", field: string, } | { "code": "InvalidGlob", glob: string, } | { "code": "EngineStarting" } | { "code": "Internal", detail: string, };
