// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backfill } from "./Backfill";
import type { Feature } from "./Feature";
import type { Install } from "./Install";

/**
 * One search feature at a glance (`features_status`, `engine://features`).
 */
export type FeatureStatus = { feature: Feature, 
/**
 * What the user wants (config).
 */
enabled: boolean, 
/**
 * Bytes to download, shown before consent.
 */
download_size: number, install: Install, 
/**
 * Files still being brought up to date after the feature came online.
 */
backfill: Backfill | null, };
