// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which optional search features the user wants (ADR-0010). Desired state
 * only: whether each one is downloaded is on disk, see `features`.
 */
export type FeaturesConfig = { meaning: boolean, image_text: boolean, image_visual: boolean, };
