// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileErrorCode } from "./FileErrorCode";

/**
 * A file in `error` (`list_errors`). The UI shows `code`, localized;
 * `detail` is diagnostic text for logs and "copy details".
 */
export type FileError = { file_id: number, path: string, code: FileErrorCode, detail: string, attempts: number, };
