// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a file failed (`files.error_code`, `list_errors`): a stable code the
 * UI localizes. `files.error` keeps the diagnostic text.
 */
export type FileErrorCode = "permission_denied" | "locked" | "read_failed" | "extract_failed" | "timed_out" | "crashed" | "embed_failed" | "write_failed" | "other";
