// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a root's last probe or watch attempt found (`roots.status`).
 */
export type Health = "ok" | "permission_denied" | "missing" | "watch_failed";
