// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the engine is doing (`get_status`, `engine://status`).
 */
export type IndexState = "idle" | "scanning" | "indexing" | "paused";
