// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexState } from "./IndexState";
import type { RootStatus } from "./RootStatus";

export type IndexStatus = { state: IndexState, 
/**
 * Files `pending` or `indexing`.
 */
queued: number, indexed: number, skipped: number, errors: number, 
/**
 * The file most recently started, while indexing.
 */
current_file: string | null, roots: Array<RootStatus>, };
