// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kind } from "./Kind";

export type IndexingConfig = { exclude_globs: Array<string>, include_hidden: boolean, follow_symlinks: boolean, max_file_size_mb: number, 
/**
 * Kinds that get content extraction; others are indexed by filename
 * only. An unknown name fails deserialization, listing the valid ones.
 */
file_types: Array<Kind>, pause_on_battery: boolean, worker_threads: number, max_image_megapixels: number, reconcile_interval_hours: number, };
