// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadError } from "./DownloadError";

/**
 * Whether a feature's download is on disk (ADR-0010). Independent of
 * `FeatureStatus::enabled`.
 */
export type Install = { "state": "not_installed" } | { "state": "downloading", bytes: number, total: number, } | { "state": "installed", size_bytes: number, } | { "state": "failed", code: DownloadError, };
