// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Matches the `files.kind` column in `migrations/0001_init.sql`; the serde
 * names are the same strings, used by `indexing.file_types`.
 */
export type Kind = "text" | "code" | "pdf" | "office" | "image" | "other";
