// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `system` resolves any `es-*` OS locale to Spanish, everything else to
 * English (resolution happens in the UI; the core only stores the choice).
 */
export type Language = "system" | "en" | "es";
