// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a result matched (SPEC.md §5.6): the UI shows a badge per source.
 */
export type MatchSource = "keyword" | "semantic" | "visual" | "ocr" | "qr" | "filename";
