// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Health } from "./Health";

export type RootStatus = { id: number, path: string, enabled: boolean, status: Health, };
