// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kind } from "./Kind";
import type { MatchSource } from "./MatchSource";
import type { Snippet } from "./Snippet";

/**
 * One search result with what the UI needs to render it (`search`).
 */
export type SearchResult = { file_id: number, path: string, file_name: string, kind: Kind, score: number, 
/**
 * `None` for a match on the image alone.
 */
snippet: Snippet | null, page: number | null, 
/**
 * Inside the thumbnail cache; `lib/ipc.ts` turns it into an asset URL.
 */
thumb_path: string | null, 
/**
 * Unix milliseconds.
 */
modified_at: number, match_sources: Array<MatchSource>, };
