// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A search query (`search`, SPEC.md §5.7).
 */
export type SearchRequest = { query: string, 
/**
 * `ui.max_results` when `null`.
 */
limit: number | null, };
