// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A snippet plus the ranges of its matched terms, in UTF-16 code units as
 * JavaScript indexes strings (`text.slice(start, end)`).
 */
export type Snippet = { text: string, highlights: Array<[number, number]>, };
