// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Search-window transparency (ADR-0010).
 */
export type TransparencyMode = "match_system" | "always" | "never";
