// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";
import type { TransparencyMode } from "./TransparencyMode";

export type UiConfig = { hotkey: string, theme: string, max_results: number, launch_at_login: boolean, language: Language, transparency_mode: TransparencyMode, 
/**
 * Alpha of the tint drawn over the native effect.
 */
transparency_intensity: number, };
