//! SPEC.md §7 M4: "Decoding a 48 MP HEIC keeps the RSS delta < 400 MB and
//! completes in < 3 s."
//!
//! No real 48 MP HEIC exists to commit (phones cap HEIC at 12 MP, and a real
//! one would be too large for the repo anyway), so this runs against a file
//! generated by `tools/synthetic_heic_48mp.py`, which is a tile-gridded HEIC
//! like a phone's. This test checks the time; the RSS half needs an external
//! poller (`psutil` at 5 ms was used, see docs/progress.md), since Rust has
//! no portable way to read peak RSS.

use std::path::PathBuf;
use std::time::{Duration, Instant};

#[test]
#[ignore = "needs MAGI_HEIC_48MP=<path to a 48 MP HEIC> from tools/synthetic_heic_48mp.py"]
fn a_48_megapixel_heic_decodes_within_the_time_budget() {
    let path = PathBuf::from(std::env::var("MAGI_HEIC_48MP").expect("MAGI_HEIC_48MP"));
    let bytes = std::fs::read(&path).unwrap();

    let start = Instant::now();
    let image = magi_core::extract::image::decode_bounded(&path, &bytes, 64).unwrap();
    let elapsed = start.elapsed();

    assert!(
        u64::from(image.width()) * u64::from(image.height()) >= 48_000_000,
        "{}x{} is not 48 MP",
        image.width(),
        image.height()
    );
    assert!(
        elapsed < Duration::from_secs(3),
        "decoding took {elapsed:?}"
    );
}
