[package]
name = "magi-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
magi-core = { path = "../magi-core" }
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
ctrlc = { workspace = true }
sysinfo = { workspace = true }
